config/routes.rb
Kratos::Application.routes.draw do

  scope '/su' do

    devise_for :users,
      :path_names => { :sign_in => 'in', :sign_out => 'out' },
      :path_prefix => 'su'

    resources :users
    resources :auth_tokens, :only => [:create, :destroy]
    root :to => 'users#index'

  end

  resources :members
  resources :parties
  root :to => "members#index"

end

app/models/party.rb
require 'uuid_helper'

class Party < ActiveRecord::Base

  include UUIDHelper
  nilify_blanks
  set_primary_key :uuid

  has_many :coalitionships, :primary_key => 'uuid', :foreign_key => 'party_uuid'

  validates :uuid, :uniqueness => true
  validates :name, :length => { :minimum => 1, :maximum => 255 }
  validates :name_in_malay, :length => { :minimum => 1, :maximum => 255 }
  validates :founded_in, :numericality => { :greater_than_or_equal_to => 1900, :less_than => 2100 }
  validates :disbanded_in, :numericality => { :greater_than_or_equal_to => 1900, :less_than => 2100 }, :allow_nil => true

  accepts_nested_attributes_for :coalitionships

  def to_param
    uuid
  end

  def coalition
    if (c = coalitionships.where(party_uuid: uuid, parted_at: nil).first)
      c.coalition
    end
  end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController

  before_filter :authenticate_user!, :only => [:create, :update, :destroy]
  load_and_authorize_resource

  def index
    @parties = Party.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @parties.as_json(:methods => [:coalition]) }
    end
  end
  
  def show
    @party = Party.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @party.as_json(:methods => [:coalition]) }
    end
  end

  def new
    @party = Party.new
    @party.coalitionships.build
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @party.as_json(:methods => [:coalition]) }
    end
  end

  def edit
    @party = Party.find(params[:id])
    @party.coalitionships.present? ? @party.coalitionships : @party.coalitionships.build
  end

  def create
    @party = Party.new(params[:party] || ActiveSupport::JSON.decode(request.body.read))

    respond_to do |format|
      if @party.save
        format.html { redirect_to @party, notice: 'Party was successfully created.' }
        format.json { render json: @party, status: :created, location: @party }
      else
        format.html { render action: "new" }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @party = Party.find(params[:id])

    respond_to do |format|
      if @party.update_attributes(params[:party] || ActiveSupport::JSON.decode(request.body.read))
        format.html { redirect_to @party, notice: 'Party was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @party = Party.find(params[:id])
    @party.destroy

    respond_to do |format|
      format.html { redirect_to parties_url }
      format.json { head :ok }
    end
  end
end

app/views/parties/_form.html.erb
<%= simple_form_for(@party) do |f| %>

  <% if @party.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@party.errors.count, "error") %> prohibited this member from being saved:</h2>
      <ul>
      <% @party.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= field_set_tag do %>
    <% if @party.persisted? %>
      <%= f.input :uuid, :label => 'UUID', :readonly => true, :hint => 'Auto-generated UUID, not changeable!' %>
    <% end %>
    <%= f.input :name %>
    <%= f.input :code %>
    <%= f.input :founded_in %>
    <%= f.input :disbanded_in %>

    <%= f.simple_fields_for :coalitionships do |co| %>
      <%= co.input :coalition_uuid, :collection => Coalition.all, :selected => (@party.coalition.try(:uuid) if @party.persisted?), :prompt => "Select coalition", :label => 'Coalition'%>

      <%= co.input :joined_at, :collection => 1970..Time.now.year %>

      <%= co.input :party_uuid, :value => @party.uuid, as: :hidden %>
    <% end %>

    
  <% end %>
  <ul class="actions">
    <li><%= f.submit %></li>
  </ul>

<% end %>

app/views/parties/edit.html.erb
<h1>Edit party</h1>
<hr/>
<% if user_signed_in? %>
  <ul class="links"><!--
 --><li><%= link_to 'Show', @party %></li><!--
 --><li><%= link_to 'Back', parties_path %></li>
  </ul>
<% end %>

<%= render 'form' %>

app/views/parties/index.html.erb
<h1>Parties</h1>
<hr/>
<% if user_signed_in? %>
  <ul class="links"><!--
 --><!--li><%= link_to 'New party', new_party_path %></li-->
  </ul>
<% end %>

<table class="resources">

  <tr>
    <th>Name</th>
    <th>Coalition</th>
    <% if user_signed_in? %>
      <th>Actions</th>
    <% end %>
  </tr>

<% @parties.each do |party| %>
  <tr>
    <td>
      <%= link_to ('%s (%s)' % [party.name, party.code]), party %>
    </td>
    <td>
      <%= party.coalition.code if party.coalition %>
    </td>
    <% if user_signed_in? %>
      <td>
        <ul class="links">
          <li><%= link_to 'Edit', edit_party_path(party) %></li>
          <li><%= link_to 'Destroy', party, confirm: 'Are you sure?', method: :delete %></li>
        </ul>
      </td>
    <% end %>
  </tr>
<% end %>

</table>

app/views/parties/new.html.erb
<h1>New party</h1>
<hr/>
<ul class="links">
  <li><%= link_to 'Back', parties_path %></li>
</ul>

<%= render 'form' %>

app/views/parties/show.html.erb
<h1><%= @party.name %> (<%= @party.code %>)</h1>
<hr/>
<ul class="links">
  <% if user_signed_in? %>
    <li><%= link_to 'Edit', edit_party_path(@party) %></li>
  <% end %>
  <li><%= link_to 'Back', parties_path %></li>
</ul>

<dl class="resource">
  <dt>Name</dt><dd><%= @party.name %></dd>
  <dt>Coalition</dt><dd><%= ('%s (%s)' % [@party.coalition.name, @party.coalition.code]) if @party.coalition %></dd>
  <dt>Founded</dt><dd><%= @party.founded_in %></dd>
  <dt>Disbanded</dt><dd><%= @party.disbanded_in %></dd>
</dl>