config/routes.rb
Kratos::Application.routes.draw do

  scope '/su' do

    devise_for :users,
      :path_names => { :sign_in => 'in', :sign_out => 'out' },
      :path_prefix => 'su'

    resources :users
    resources :auth_tokens, :only => [:create, :destroy]
    root :to => 'users#index'

  end

  resources :members
  resources :parties
  root :to => "members#index"

end

app/models/user.rb
require 'uuid_helper'

class User < ActiveRecord::Base

  include UUIDHelper
  nilify_blanks
  set_primary_key :uuid

  attr_accessible :email, :password, :remember_me, :role
  devise :database_authenticatable, :lockable, :rememberable, :timeoutable, :token_authenticatable, :trackable
  enum_attr :role, %w(admin basic anonymous)

  validates :uuid, :uniqueness => true
  validates :email, :presence => true, :uniqueness => true, :email => true
  validates :password, :length => { :within => Devise.password_length }, :allow_blank => true

  def to_param
    uuid
  end

  # See: Devise::Models::DatabaseAuthenticatable
  # See: http://stackoverflow.com/a/5070882/36397
  def update_with_password(params, *options)
    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end
    update_attributes(params, *options)
    clean_up_passwords
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update

    @user = User.find(params[:id])

    respond_to do |format|
      # See: https://github.com/plataformatec/devise/wiki/How-To%3a-Allow-users-to-edit-their-account-without-providing-a-password
      ok = unless params[:user][:password].blank?
        params[:user][:password_confirmation] = params[:user][:password]
        @user.update_with_password(params[:user])
      else
        @user.update_without_password(params[:user])
      end

      if ok
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= field_set_tag do %>
    <% if @user.persisted? %>
      <%= f.input :uuid, :label => 'UUID', :readonly => true, :hint => 'Auto-generated UUID, not changeable!' %>
    <% end %>
    <%= f.input :email, :hint => 'Login ID, must be unique.' %>
    <%= f.input :role do %>
      <%= f.enum_select :role, :disabled => :anonymous, :include_blank => false %>
    <% end %>
    <%= f.input :password do %>
      <%= f.password_field :password, :autocomplete => "off", :hint => 'Leave this blank unless you want to change the password!' %>
    <% end %>
    <% unless @user.persisted? %>
      <!--<%= f.input :password_confirmation do %>
        <%= f.password_field :password_confirmation %>
      <% end %>-->
    <% end %>
  <% end %>
  <ul class="actions">
    <li><%= f.submit %></li>
  </ul>

<% end %>

app/views/users/edit.html.erb
<h1>Edit user</h1>
<hr/>
<% if user_signed_in? %>
  <ul class="links"><!--
 --><li><%= link_to 'Show', @user %></li><!--
 --><li><%= link_to 'Back', users_path %></li>
  </ul>
<% end %>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Users</h1>
<hr/>
<ul class="links">
  <li><%= link_to 'New user', new_user_path %></li>
</ul>

<table class="resources">
  
  <tr>
    <th>Email</th>
    <th>Role</th>
    <th>Action</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to user.email, user %></td>
    <td><%= user.role.capitalize %></td>
    <td>
      <ul class="links">
        <li><%= link_to 'Edit', edit_user_path(user) %></li>
        <li><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></li>
      </ul>
    </td>
  </tr>
<% end %>

</table>

app/views/users/new.html.erb
<h1>New user</h1>
<hr/>
<ul class="links">
  <li><%= link_to 'Back', users_path %></li>
</ul>

<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.email ? @user.email[/(.+)@/, 1] : @user.uuid %> (<%= @user.role.capitalize %>)</h1>
<hr/>
<ul class="links">
  <li><%= link_to 'Edit', edit_user_path(@user) %></li>
  <li><%= link_to 'Back', users_path %></li>
</ul>

<dl class="resource">
  <dt>Email</dt><dd><%= mail_to @user.email %></dd>
  <dt>Authentication Token</dt>
  <dd>
    <% unless @user.authentication_token.blank? %>
      <span><%= @user.authentication_token %></span> |
      <%= link_to "Re-Generate", auth_tokens_path(:id => @user.id), :method => :post, :confirm => "Are you sure?"  %> |
      <%= link_to "Revoke", auth_token_path(@user), :method => :delete, :confirm => "Are you sure?"  %>
    <% else %>
      <%= link_to "Generate", auth_tokens_path(:id => @user.id), :method => :post %>
    <% end %>
  </dd>
</dl>