config/routes.rb
Kratos::Application.routes.draw do

  scope '/su' do

    devise_for :users,
      :path_names => { :sign_in => 'in', :sign_out => 'out' },
      :path_prefix => 'su'

    resources :users
    resources :auth_tokens, :only => [:create, :destroy]
    root :to => 'users#index'

  end

  resources :members
  resources :parties
  root :to => "members#index"

end

app/models/member.rb
require 'uuid_helper'

class Member < ActiveRecord::Base

  include UUIDHelper
  nilify_blanks
  set_primary_key :uuid

  has_many :party_memberships, :primary_key => 'uuid', :foreign_key => 'member_uuid'

  validates :uuid, :uniqueness => true
  validates :name, :length => { :minimum => 1, :maximum => 255 }
  validates :email, :email => true, :allow_blank => true
  validates :facebook, :url => true, :allow_blank => true
  validates :twitter, :url => true, :allow_blank => true
  validates :www, :url => true, :allow_blank => true
  validates :phone, :format => { :with => /^0[0-9]+/ }, :allow_blank => true
  validates :fax, :format => { :with => /^0[0-9]+/ }, :allow_blank => true

  def to_param
    uuid
  end

  def party
    if pm = party_memberships.where(member_uuid: uuid, parted_at: nil).first
      pm.party
    end
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  before_filter :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /members
  # GET /members.json
  def index
    @members = Member.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @members.as_json(:methods => [:party]) }
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
    @member = Member.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @member.as_json(:methods => [:party]) }
    end
  end

  # GET /members/new
  # GET /members/new.json
  def new
    @member = Member.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @member.as_json(:methods => [:party]) }
    end
  end

  # GET /members/1/edit
  def edit
    @member = Member.find(params[:id])
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(params[:member] || ActiveSupport::JSON.decode(request.body.read))

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render json: @member, status: :created, location: @member }
      else
        format.html { render action: "new" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /members/1
  # PUT /members/1.json
  def update
    @member = Member.find(params[:id])

    respond_to do |format|
      if @member.update_attributes(params[:member] || ActiveSupport::JSON.decode(request.body.read))
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member = Member.find(params[:id])
    @member.destroy

    respond_to do |format|
      format.html { redirect_to members_url }
      format.json { head :ok }
    end
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= simple_form_for(@member) do |f| %>

  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>
      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= field_set_tag do %>
    <% if @member.persisted? %>
      <%= f.input :uuid, :label => 'UUID', :readonly => true, :hint => 'Auto-generated UUID, not changeable!' %>
    <% end %>
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :facebook %>
    <%= f.input :twitter %>
    <%= f.input :www %>
    <%= f.input :phone %>
    <%= f.input :birthday %>
    <%= f.input :deceased_at %>
    <%= f.input :biography, :hint => 'Use <a href="http://daringfireball.net/projects/markdown/syntax" target="_new">Markdown syntax</a> to produce better markup. This field also supports the non-standard <a href="http://kramdown.rubyforge.org/syntax.html" target="_new">Markdown Extra syntax</a>.' %>
    <%= f.input :more, :hint =>
      'This is an extension to support arbitrary content. Use the <a href="http://kramdown.rubyforge.org/syntax.html#definition-lists" target="_new">Markdown Extra\'s definition list</a>, e.g. ' +
      <<HTML
<pre>
Nickname
: The old man

Magnum Opus
: Phenomenology of the Spirit
</pre>
HTML
    %>
  <% end %>
  <ul class="actions">
    <li><%= f.submit %></li>
  </ul>

<% end %>

app/views/members/edit.html.erb
<h1>Edit member</h1>
<hr/>
<% if user_signed_in? %>
  <ul class="links"><!--
 --><li><%= link_to 'Show', @member %></li><!--
 --><li><%= link_to 'Back', members_path %></li>
  </ul>
<% end %>

<%= render 'form' %>

app/views/members/index.html.erb
<h1>Members</h1>
<hr/>
<% if user_signed_in? %>
  <ul class="links"><!--
 --><!--li><%= link_to 'New member', new_member_path %></li-->
  </ul>
<% end %>

<table class="resources">

  <tr>
    <th>Name</th>
    <th>Party</th>
    <th>Connect</th>
    <% if user_signed_in? %>
      <th>Actions</th>
    <% end %>
  </tr>

<% @members.each do |member| %>
  <tr>
    <td>
      <%= link_to member.name, member %>
    </td>
    <td>
      <%= link_to member.party.code, member.party if member.party %>
    </td>
    <td>
      <ul class="image-links">
        <% if member.email %>
          <li><%= mail_to(member.email, content_tag(:span, 'Email', :class => 'icon icon-email'), :encode => 'hex') if member.email %></li>
        <% end %>
        <% if member.facebook %>
          <li><a href="<%= member.facebook %>" target="_new"><span class="icon icon-facebook">Facebook</span></a></li>
        <% end %>
        <% if member.twitter %>
          <li><a href="<%= member.twitter %>" target="_new"><span class="icon icon-twitter">Twitter</span></a></li>
        <% end %>
        <% if member.www %>
          <li><a href="<%= member.www %>" target="_new"><span class="icon icon-www">Site</span></a></li>
        <% end %>
      </ul>
    </td>
    <% if user_signed_in? %>
      <td>
        <ul class="links">
          <li><%= link_to 'Edit', edit_member_path(member) %></li>
          <li><%= link_to 'Destroy', member, confirm: 'Are you sure?', method: :delete %></li>
        </ul>
      </td>
    <% end %>
  </tr>
<% end %>

</table>

app/views/members/new.html.erb
<h1>New member</h1>
<hr/>
<ul class="links">
  <li><%= link_to 'Back', members_path %></li>
</ul>

<%= render 'form' %>

app/views/members/show.html.erb
<h1><%= @member.name %></h1>
<hr/>
<ul class="links">
  <% if user_signed_in? %>
    <li><%= link_to 'Edit', edit_member_path(@member) %></li>
  <% end %>
  <li><%= link_to 'Back', members_path %></li>
</ul>

<dl class="resource">
  <% unless @member.biography.blank? %>
    <dt id="member-biography" class="hidden">Biography</dt><dd><%= markup @member.biography %></dd>
  <% end %>
  <dt>Party</dt>
  <dd>
    <% if @member.party %>
      <%= link_to(@member.party.name, @member.party) %>
      <% if @member.party.coalition %>
        (<%= @member.party.coalition.code %>)
      <% end %>
    <% else %>
      Independent
    <% end %>
  </dd>
  <dt>Email</dt><dd><%= mail_to(@member.email, nil, :encode => 'hex', :replace_at => '_at_', :replace_dot => '_dot_') if @member.email %></dd>
  <dt>Facebook</dt><dd><%= link_to(@member.facebook, @member.facebook, :target => '_new') if @member.facebook %></dd>
  <dt>Twitter</dt><dd><%= link_to(@member.twitter, @member.twitter, :target => '_new') if @member.twitter %></dd>
  <dt>WWW</dt><dd><%= link_to(@member.www, @member.www, :target => '_new') if @member.www %></dd>
  <dt>Phone</dt><dd><%= @member.phone %></dd>
  <dt>Birthday</dt><dd><%= @member.birthday %></dd>
  <dt>Deceased at</dt><dd><%= @member.deceased_at %></dd>
  <% unless @member.more.blank? %>
    <dt id="member-more" class="hidden">More</dt><dd><%= markup @member.more %></dd>
  <% end %>
</dl>